server:
  port: 9010
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

keycloak:
    client:
      clientId: login-app
      clientSecret: e12557ee-30bf-4c7d-968c-4e4ac45b89de
      accessTokenUri: http://localhost:8180/auth/realms/SpringBootKeycloak/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8180/auth/realms/SpringBootKeycloak/protocol/openid-connect/auth
      authenticationScheme: header
      clientAuthenticationScheme: header
      #authenticationScheme: query
      #clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8180/auth/realms/SpringBootKeycloak/protocol/openid-connect/userinfo
logging:
  level:
    org.springframework.security: DEBUG
