version: '2'
services:
  grafana:
    ports:
    - "3000:3000"
    volumes:
    - /var/lib/grafana
    links:
    - prometheus
    image: grafana/grafana
  prometheus:
    ports:
    - "9090:9090"
    volumes:
    - ~/Documents/docker/prometheus/etc:/etc/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
