apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #creationTimestamp: null
  labels:
    io.kompose.service: esdata
  name: esdata
  namespace: dotcms
spec:
  storageClassName: dotcms-esdata-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
