apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #creationTimestamp: null
  labels:
    io.kompose.service: pgdata
  name: pgdata
  namespace: dotcms
spec:
  storageClassName: dotcms-pgdata-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
