kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-postgresql
  labels:
    type: local
spec:
  storageClassName: postgresql-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-pv/postgresql"
