---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-boot
  labels:
    name: zipkin-boot
  namespace: zipkin-boot
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 3380
    targetPort: 3380
    nodePort: 3380
  selector:
    name: zipkin-boot
