server:
  port: 3480

spring:
  application:
    # This ends up as the service name in zipkin
    name: fluentd-boot
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://${ZIPKIN_HOST:192.168.99.101}:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false