apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger-editor
  namespace: swagger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swagger-editor
    spec:
      containers:
      - image: swaggerapi/swagger-editor
        imagePullPolicy: IfNotPresent
        name: swagger-editor
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: swagger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - image: swaggerapi/swagger-ui
        imagePullPolicy: IfNotPresent
        name: swagger-ui
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-editor-service
  namespace: swagger
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: swagger-editor
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui-service
  namespace: swagger
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: swagger-ui
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swagger-ingress
  namespace: swagger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: swagger-editor.bpwizard.com
    http:
      paths:
      - path: /
        backend:
          serviceName: swagger-editor-service
          servicePort: 8080
  - host: swagger-ui.bpwizard.com
    http:
      paths:
      - path: /
        backend:
          serviceName: swagger-ui-service
          servicePort: 8080
