kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-redis
  labels:
    type: local
spec:
  storageClassName: redis-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-pv/redis"
