language: node_js
node_js:
- 4.2.4
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem update --system
install:
- cd log4js
- npm install
- npm install -g bower grunt-cli
before_script:
- npm install
script:
- grunt --gruntfile "Gruntfile.js" build --verbose --force
deploy:
  provider: releases
  api_key:
    secure: D3OkluDRa3mkyQAYPMCrbIqvIpZAGOsjqO/21myRDa7MiRjkZJgg2TMxfSTfUsnSf4aMKvLybvD7+YWd1015U7OqFR+I0hkwV49DNlQgw9/Gh7mFAfrM3wO7qibSKdTeaph76hmCQfNxN9UWEdyrnEzRooBlwJDa/skq65z70hc=
  file: log4js\target\*.zip
  skip_cleanup: true
  on:
    repo: stritti/log4js
    branch: master	
