version: '3.0'

networks:
  http_net:
  db_net:
  es_net:
  hz_net:

volumes:
  esdata:
  cms-shared:
  pgdata:

services:

  http:
    image: dotcms/haproxy:1.8-prelim
    environment:
      "HAPROXY_CERT_PATH": '/srv/config/haproxy.crt'
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - /data/shared/haproxy/haproxy.crt:/srv/config/haproxy.crt:ro
    networks:
      - http_net

  hazelcast:
    image: dotcms/hazelcast:3.9.2-prelim
    environment:
      "MIN_HEAP_SIZE": '128m'
      "MAX_HEAP_SIZE": '512m'
      "HAZELCAST_MANCENTER_URL": 'http://hazelcast-mancenter:8080/mancenter'
    networks:
      - hz_net

  hazelcast-mancenter:
    image: dotcms/hazelcast-mancenter:3.9.2-prelim
    environment:
      "HZ_SVC_NAMES": 'hazelcast'
    ports:
      - "8080:8080"
    networks:
      - hz_net

  elasticsearch-static:
    image: dotcms/elasticsearch:6.1.3-prelim
    environment:
      "ELASTICSEARCH_HEAP_SIZE": '1024m'
      "ELASTICSEARCH_SERVICE_NAMES": 'elasticsearch-static,elasticsearch'
      "ELASTICSEARCH_SERVICE_DELAY_MIN": '1'
      "ELASTICSEARCH_SERVICE_DELAY_STEP": '1'
      "ELASTICSEARCH_SERVICE_DELAY_MAX": '2'
    volumes:
      - esdata:/data
    networks:
      - es_net

  elasticsearch:
    image: dotcms/elasticsearch:6.1.3-prelim
    depends_on:
      - elasticsearch-static
    environment:
      "ELASTICSEARCH_HEAP_SIZE": '1024m'
      "ELASTICSEARCH_SERVICE_NAMES": 'elasticsearch-static,elasticsearch'
      "ELASTICSEARCH_SERVICE_DELAY_MIN": '3'
      "ELASTICSEARCH_SERVICE_DELAY_MAX": '30'
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:5.0.0-prelim
    environment:
      "TOMCAT_HEAP_SIZE": '1500m'
      "HAZELCAST_SERVICE_NAMES": 'hazelcast'
      "ELASTICSEARCH_SERVICE_NAMES": 'elasticsearch-static,elasticsearch'
      # To enable java debugging, set TOMCAT_JAVA_OPTS to values needed.  Will then need to setup proxy to
      #     debug port or expose port below.  Example debug string provided below.
      # "TOMCAT_JAVA_OPTS": '-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000'

      # To enable profiler, must use following java options and setup proxy to port 4000 or
      #     configure bind address to 0.0.0.0 and expose port 4000 below.
      # "TOMCAT_JAVA_OPTS": '-javaagent:/srv/dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/profiler/profiler.jar'
    depends_on:
      - elasticsearch-static
      - hazelcast
      - db
      - http
    volumes:
      - cms-shared:/data/shared
      #- ${PWD}/license.zip:/data/shared/assets/license.zip
      - ${PWD}/license.dat:/data/local/dotsecure/license/license.dat
      - ${PWD}/cms/plugins:/srv/plugins
    # ports:
      # 9200 is for ES HTTP Interface - not needed unless wanting to troubleshoot or debug ES issues
      # - "9200:9200"
      # 8000 is for debugging dotcms - allows remote debugger to be attached
      # - "8000:8000"
    networks:
      - http_net
      - db_net
      - es_net
      - hz_net
    healthcheck:
      test: ["CMD-SHELL", "/srv/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 3
      #start_period: 180s

  db:
    image: dotcms/postgres:9.6-prelim
    environment:
      "NULL": "null"
      #POSTGRES_USER: dotcms
      #POSTGRES_PASSWORD: dockermydotcms
    volumes:
      - pgdata:/data/pg
    networks:
      - db_net
