kind: PersistentVolume
apiVersion: v1
metadata:
  name: zipkin-mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-pv/zipkin/mysql"
