apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube-pv/jenkins
