apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: springcloud-bpm
  labels:
    tier: springcloud
  namespace: springcloud
spec:
  selector:
    matchLabels:
      tier: springcloud
  endpoints:
  - port: web            # works for different port numbers as long as the name matches
    interval: 10s        # scrape the endpoint every 10 seconds
  #jobLabel: springcloud
  #namespaceSelector:
    #matchNames:
    #-springcloud