apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-springcloud
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      tier: springcloud
  resources:
    requests:
      memory: 400Mi
