kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-mysql
  labels:
    type: local
spec:
  storageClassName: mysql-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-pv/mysql"
