kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-grafana
  labels:
    type: local
spec:
  storageClassName: grafana-pv
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-pv/grafana"
