kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-nexus
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/fli/volume-nexus"
