apiVersion: v1
kind: ReplicationController
metadata:
    name: Kibana-logging
    namespace: kube-system
    labels:
        k8s-app: Kibana-logging
        kubernetes.io/cluster-service: "true"
spec:
    replicas: 1
    selector:
        k8s-app: Kibana-logging
    template:
        metadata:
            labels:
                k8s-app: Kibana-logging
                kubernetes.io/cluster-service: "true"
        spec:
            containers:
            - name: Kibana
                image: <; Your kb-image >
                ports:
                    - name: Kibana-port
                    containerPort: 5601
                    